import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Playfair_Display, Playwrite_GB_J } from "next/font/google";
import Script from "next/script";
import AppToastViewport from "@/components/AppToast";
import SiteFooter from "@/components/SiteFooter";
import InitialPreloader from "@/components/InitialPreloader";
import BackToTop from "@/components/BackToTop";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const playfair = Playfair_Display({
  variable: "--font-serif",
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
});

const handwriting = Playwrite_GB_J({
  variable: "--font-hand",
  weight: "400",
  adjustFontFallback: false,
  display: "swap",
});

// Montserrat/Raleway/Oswald/Dancing Script used to load here too. They're only used as canvas
// font-family choices in the /card-editor tool, which now loads them itself
// (src/app/card-editor/layout.tsx) — every other page no longer pays for those 4 font fetches.

export const runtime = "nodejs";

// Validate and normalise to bare origin so a misconfigured env var like
// "https://hushare.space/</script>" cannot break the JSON-LD <script> block.
const SITE_URL = (() => {
  const raw = process.env.NEXT_PUBLIC_SITE_URL ?? "https://hushare.space";
  try { return new URL(raw).origin; } catch { return "https://hushare.space"; }
})();
const SITE_NAME = "Hushare";
const TAGLINE = "Shared photo albums from one link";
const DESCRIPTION =
  "Create a shared photo album in seconds. Guests add photos from one link - no app, no sign-up. Perfect for weddings, trips, reunions, and every moment worth keeping.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} - ${TAGLINE}`,
    template: `%s - ${SITE_NAME}`,
  },
  description: DESCRIPTION,
  applicationName: SITE_NAME,
  authors: [{ name: SITE_NAME, url: SITE_URL }],
  creator: SITE_NAME,
  publisher: SITE_NAME,
  category: "photography",
  keywords: [
    "shared photo album",
    "collaborative photo album",
    "wedding photo sharing",
    "wedding guest photo app",
    "event photo sharing",
    "guest photo collection",
    "QR code photo sharing",
    "share photos without an app",
    "no sign up photo album",
    "party photo sharing",
    "trip photo album",
    "family photo sharing",
    "free photo sharing",
    "group photo album",
    "Hushare",
  ],
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: `${SITE_NAME} - ${TAGLINE}`,
    description: DESCRIPTION,
    locale: "en_US",
    images: [
      {
        url: "/wedding.jpg",
        width: 700,
        height: 1052,
        alt:
          "Hushare - shared photo album for weddings, trips, and the moments worth keeping",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE_NAME} - ${TAGLINE}`,
    description: DESCRIPTION,
    images: ["/wedding.jpg"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  verification: {
    google: "c69Mks9gyxr7Q0EBB3cP4CGlbSFyQxTvxes0pu0eQYI",
    yandex: "0d69c5ed99d50ec6",
    other: {
      "msvalidate.01": "22AB3EC00DB3D5ECE126BEDD09A3DD8E",
    },
  },
  // Icons are auto-generated by Next from the app-dir convention files:
  //   src/app/favicon.ico (multi-res 16/32 — used by browser tabs)
  //   src/app/icon.png (64x64)  and  src/app/apple-icon.png (500x500)
  // Do NOT also declare `icons` here — it produced 5 duplicate/conflicting
  // <link rel="icon"> tags (incl. a legacy `shortcut icon`) which left browsers
  // picking the wrong/low-res icon.
  referrer: "origin-when-cross-origin",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FDFAF5" },
    { media: "(prefers-color-scheme: dark)", color: "#630826" },
  ],
  colorScheme: "light",
  width: "device-width",
  initialScale: 1,
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${SITE_URL}#organization`,
      name: SITE_NAME,
      url: SITE_URL,
      logo: `${SITE_URL}/logo/logo-favicon.png`,
      foundingLocation: {
        "@type": "Place",
        name: "Yerevan, Armenia",
      },
    },
    {
      "@type": "WebSite",
      "@id": `${SITE_URL}#website`,
      url: SITE_URL,
      name: SITE_NAME,
      description: DESCRIPTION,
      publisher: { "@id": `${SITE_URL}#organization` },
      inLanguage: "en",
    },
    {
      "@type": "WebApplication",
      "@id": `${SITE_URL}#app`,
      name: SITE_NAME,
      url: SITE_URL,
      description: DESCRIPTION,
      applicationCategory: "PhotoApplication",
      operatingSystem: "Any (Web browser)",
      browserRequirements:
        "Requires JavaScript. Works in any modern browser.",
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD",
      },
      featureList: [
        "No account or sign-up required",
        "Share albums via link or QR code",
        "Unlimited contributors per album",
        "Private link-based ownership",
        "Download every photo as a ZIP",
      ],
      publisher: { "@id": `${SITE_URL}#organization` },
    },
    {
      "@type": "HowTo",
      "@id": `${SITE_URL}#howto`,
      name: "How to create a shared photo album with Hushare",
      description:
        "Create a shared album, share the link, and let everyone add photos - in three steps, no account required.",
      totalTime: "PT1M",
      tool: [{ "@type": "HowToTool", name: "Any web browser" }],
      step: [
        {
          "@type": "HowToStep",
          position: 1,
          name: "Name your album",
          text: "Give your album a name on the Hushare home page. You instantly receive a private link only you control - no sign-up, no app.",
          url: `${SITE_URL}#step-name`,
        },
        {
          "@type": "HowToStep",
          position: 2,
          name: "Share the link",
          text: "Send the link by text, post a QR code at your event, or drop it in a group chat. Anyone with the link can view and add photos.",
          url: `${SITE_URL}#step-share`,
        },
        {
          "@type": "HowToStep",
          position: 3,
          name: "Keep it forever",
          text: "Photos arrive from everyone you invited. Active albums live on indefinitely; download the whole album as a ZIP anytime.",
          url: `${SITE_URL}#step-keep`,
        },
      ],
    },
    {
      "@type": "WebPage",
      "@id": `${SITE_URL}#webpage`,
      url: SITE_URL,
      name: `${SITE_NAME} - ${TAGLINE}`,
      description: DESCRIPTION,
      inLanguage: "en",
      isPartOf: { "@id": `${SITE_URL}#website` },
      primaryImageOfPage: {
        "@type": "ImageObject",
        url: `${SITE_URL}/wedding.jpg`,
      },
      breadcrumb: { "@id": `${SITE_URL}#breadcrumb` },
    },
    {
      "@type": "BreadcrumbList",
      "@id": `${SITE_URL}#breadcrumb`,
      itemListElement: [
        {
          "@type": "ListItem",
          position: 1,
          name: "Home",
          item: SITE_URL,
        },
      ],
    },
    {
      "@type": "FAQPage",
      "@id": `${SITE_URL}#faq`,
      mainEntity: [
        {
          "@type": "Question",
          name: "Do guests need an account to add photos?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "No. Anyone with your album link can view and add photos - no sign-up, no app, no download. Hushare is designed so the only friction between a guest and the album is tapping the link.",
          },
        },
        {
          "@type": "Question",
          name: "How long does Hushare keep my photos?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Free albums are preserved as long as they remain active. If an album sits untouched by everyone for 3 months, it is automatically retired and its media is deleted (we email a warning first). Active albums live on. Paid tiers remove this inactivity rule and keep albums a year after cancellation.",
          },
        },
        {
          "@type": "Question",
          name: "Is Hushare really free?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes. Free albums are free to create, share, upload to, and download from, with no credit card required. Paid tiers add custom URLs, passwords, larger uploads, Studio Collections, and no inactivity retirement.",
          },
        },
        {
          "@type": "Question",
          name: "Can I use a QR code at a wedding or event?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes. Every album has a unique link you can turn into a QR code and print on table cards, invitations, programs, or a welcome sign. Guests scan it and start adding photos instantly.",
          },
        },
        {
          "@type": "Question",
          name: "Can I download all the photos at once?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes. From the owner view of your album, you can download the full collection as a single ZIP file - originals, not compressed thumbnails.",
          },
        },
        {
          "@type": "Question",
          name: "Who can see my album?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Only people with the link. Albums are unlisted - they are not indexed by search engines and cannot be discovered by browsing the site. Share the link only with the people you want to invite.",
          },
        },
        {
          "@type": "Question",
          name: "What happens if I lose my owner link?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "The owner link is how Hushare recognises you as the album creator. Bookmark it as soon as you create an album, or forward it to yourself. If you do lose it, contact us with your album name and approximate creation date and we will verify you manually.",
          },
        },
        {
          "@type": "Question",
          name: "What photo formats and sizes are supported?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Free albums support JPG, PNG, HEIC, and WebP images up to 25 MB each, plus MP4, MOV, or WebM videos up to 50 MB. Pro and Studio albums support uploads up to 200 MB.",
          },
        },
      ],
    },
  ],
};

// Exact text content of the two inline (non-JSON-LD) <script> tags below. Kept as named
// constants — rather than inline template strings — so PRELOADER_INIT_SCRIPT_SHA256 /
// GA_INIT_SCRIPT_SHA256 in next.config.ts can be computed from and verified against the exact
// same string that gets rendered. If either script's content changes, its CSP hash must be
// recomputed too, or the script will be silently blocked (see next.config.ts's comment).
const PRELOADER_INIT_SCRIPT =
  "try{if(window.localStorage.getItem('hushare.initialPreloaderSeen')!=='1'){document.body.classList.add('hush-page-preloading','hush-scroll-locked')}}catch(e){document.body.classList.add('hush-page-preloading','hush-scroll-locked')}"
const GA_INIT_SCRIPT =
  "window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','G-5JMF0RM5Q6');"

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} ${handwriting.variable} h-full antialiased`}
    >
      <head>
        <link rel="preconnect" href="https://yqngmyjquwemwogdyuwv.supabase.co" />
        <link rel="preconnect" href="https://videos.hushare.space" />
        <link rel="preconnect" href="https://iframe.videodelivery.net" />
        <link rel="preconnect" href="https://videodelivery.net" />
        <link rel="dns-prefetch" href="https://challenges.cloudflare.com" />
      </head>
      <body className="min-h-full flex flex-col">
        <script dangerouslySetInnerHTML={{ __html: PRELOADER_INIT_SCRIPT }} />
        {/* type="application/ld+json" is inert data, not executable script — browsers never run
            it under script-src, so it is unaffected by CSP either way. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, '\\u003c') }}
        />
        {process.env.NODE_ENV === 'production' && (
          <>
            <Script
              src="https://www.googletagmanager.com/gtag/js?id=G-5JMF0RM5Q6"
              strategy="afterInteractive"
            />
            <Script id="google-analytics" strategy="afterInteractive"
              dangerouslySetInnerHTML={{ __html: GA_INIT_SCRIPT }}
            />
          </>
        )}
        <InitialPreloader />
        {children}
        <SiteFooter />
        <BackToTop />
        <AppToastViewport />
      </body>
    </html>
  );
}
