// One-off generator: downloads every ISO-3166-1 flag into public/flags/ and writes the English
// country-name map used by the admin dashboard.
//
// SELF-HOSTED on purpose. The site's CSP is `img-src 'self' data: blob:`, so a flag CDN is blocked
// at runtime — and rightly, because an admin page should not tell a third party which countries the
// owner is looking at. Emoji flags were not an option either: Windows ships no regional-indicator
// glyphs, so they render as the very two-letter codes this replaces (see LocaleFlag.tsx, which
// reached the same conclusion for the language switcher).
//
// The names are baked into a TypeScript file rather than resolved with Intl at runtime, so the
// dashboard cannot depend on the Workers runtime shipping a particular ICU build.
//
// PNGs at 80px wide, not SVG. The SVG set came to 4.1MB because a dozen countries carry a full coat
// of arms — El Salvador alone is 244KB — and every one of those would be downloaded, parsed and
// rasterised to draw a 16px-tall rectangle in a list. The whole PNG set is about 80KB.
//
// Re-run with:  node scripts/fetch-flags.mjs
import { mkdirSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const OUT_DIR = join(process.cwd(), 'public', 'flags')
mkdirSync(OUT_DIR, { recursive: true })

const display = new Intl.DisplayNames(['en'], { type: 'region' })
const A = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('')
const codes = []
for (const a of A) {
  for (const b of A) {
    const cc = a + b
    let name
    try { name = display.of(cc) } catch { continue }
    // A code with no name resolves to itself — those are unassigned.
    if (!name || name === cc) continue
    codes.push([cc, name])
  }
}
console.log(`[flags] ${codes.length} regions`)

let ok = 0, missing = 0
const limit = 12
let i = 0
async function worker() {
  while (i < codes.length) {
    const [cc] = codes[i++]
    const file = join(OUT_DIR, `${cc.toLowerCase()}.png`)
    if (existsSync(file)) { ok++; continue }
    try {
      const r = await fetch(`https://flagcdn.com/w80/${cc.toLowerCase()}.png`)
      if (!r.ok) { missing++; continue }
      const buf = Buffer.from(await r.arrayBuffer())
      // A PNG starts with the 8-byte signature; anything else is an error page.
      if (buf.length < 8 || buf[0] !== 0x89 || buf[1] !== 0x50) { missing++; continue }
      writeFileSync(file, buf)
      ok++
    } catch { missing++ }
  }
}
await Promise.all(Array.from({ length: limit }, worker))
console.log(`[flags] ${ok} written, ${missing} unavailable`)

// Which flags actually landed. 28 regions have no flag available (Antarctica, the EU, assorted
// territories), and rendering an <img> for one of those would put a broken-image icon in the table.
const have = codes
  .filter(([cc]) => existsSync(join(OUT_DIR, cc.toLowerCase() + '.png')))
  .map(([cc]) => cc)

const entries = codes.map(([cc, name]) => `  ${cc}: ${JSON.stringify(name)},`).join('\n')
writeFileSync(join(process.cwd(), 'src', 'lib', 'country-names.ts'), `// GENERATED by scripts/fetch-flags.mjs — do not edit by hand.
//
// English country names, baked in rather than resolved with Intl at runtime so the dashboard does
// not depend on which ICU build the Workers runtime happens to ship.
export const COUNTRY_NAMES: Record<string, string> = {
${entries}
}

/** Full name for an ISO-3166-1 alpha-2 code, falling back to the code itself. */
export function countryName(code: string): string {
  if (!code) return ''
  return COUNTRY_NAMES[code.toUpperCase()] ?? code.toUpperCase()
}

/** Codes with a flag image in /public/flags. Checked before rendering, so never a broken image. */
export const FLAG_CODES = new Set(${JSON.stringify(have)})

/** Path to a country's flag, or null when we do not have one. */
export function flagSrc(code: string): string | null {
  const cc = (code || '').toUpperCase()
  return FLAG_CODES.has(cc) ? '/flags/' + cc.toLowerCase() + '.png' : null
}
`)
console.log('[flags] wrote src/lib/country-names.ts')
